// <auto-generated />
using FarmerCropMarketing.Models.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace FarmerCropMarketing.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20210108131938_init")]
    partial class init
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseIdentityColumns()
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.1");

            modelBuilder.Entity("FarmerCropMarketing.Models.Admin", b =>
                {
                    b.Property<int>("Admin_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.HasKey("Admin_id");

                    b.ToTable("Admin");
                });

            modelBuilder.Entity("FarmerCropMarketing.Models.Buissnessman", b =>
                {
                    b.Property<int>("Buissnessman_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.HasKey("Buissnessman_id");

                    b.ToTable("Buissnessmen");
                });

            modelBuilder.Entity("FarmerCropMarketing.Models.Cart", b =>
                {
                    b.Property<int>("Cart_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.HasKey("Cart_id");

                    b.ToTable("Cart");
                });

            modelBuilder.Entity("FarmerCropMarketing.Models.Crops", b =>
                {
                    b.Property<int>("Crops_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.HasKey("Crops_id");

                    b.ToTable("Crops");
                });

            modelBuilder.Entity("FarmerCropMarketing.Models.Farmers", b =>
                {
                    b.Property<int>("Farmers_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.HasKey("Farmers_id");

                    b.ToTable("Farmers");
                });

            modelBuilder.Entity("FarmerCropMarketing.Models.Orders", b =>
                {
                    b.Property<int>("Orders_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.HasKey("Orders_id");

                    b.ToTable("Orders");
                });
#pragma warning restore 612, 618
        }
    }
}
